
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ProjectStatus = {
  IDEA: 'IDEA',
  IN_PROGRESS: 'IN_PROGRESS',
  BETA: 'BETA',
  LIVE: 'LIVE',
  ARCHIVED: 'ARCHIVED'
} as const

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus]


export const TechCategory = {
  FRONTEND: 'FRONTEND',
  BACKEND: 'BACKEND',
  DATABASE: 'DATABASE',
  DEVOPS: 'DEVOPS',
  MOBILE: 'MOBILE',
  AI_ML: 'AI_ML',
  DESIGN: 'DESIGN',
  OTHER: 'OTHER'
} as const

export type TechCategory = (typeof TechCategory)[keyof typeof TechCategory]
