
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProjectCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProjectCategory
 * 
 */
export type ProjectCategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectCategoryPayload>

export type AggregateProjectCategory = {
  _count: ProjectCategoryCountAggregateOutputType | null
  _min: ProjectCategoryMinAggregateOutputType | null
  _max: ProjectCategoryMaxAggregateOutputType | null
}

export type ProjectCategoryMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  category: string | null
}

export type ProjectCategoryMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  category: string | null
}

export type ProjectCategoryCountAggregateOutputType = {
  id: number
  projectId: number
  category: number
  _all: number
}


export type ProjectCategoryMinAggregateInputType = {
  id?: true
  projectId?: true
  category?: true
}

export type ProjectCategoryMaxAggregateInputType = {
  id?: true
  projectId?: true
  category?: true
}

export type ProjectCategoryCountAggregateInputType = {
  id?: true
  projectId?: true
  category?: true
  _all?: true
}

export type ProjectCategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectCategory to aggregate.
   */
  where?: Prisma.ProjectCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectCategories to fetch.
   */
  orderBy?: Prisma.ProjectCategoryOrderByWithRelationInput | Prisma.ProjectCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProjectCategories
  **/
  _count?: true | ProjectCategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectCategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectCategoryMaxAggregateInputType
}

export type GetProjectCategoryAggregateType<T extends ProjectCategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateProjectCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProjectCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateProjectCategory[P]>
}




export type ProjectCategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectCategoryWhereInput
  orderBy?: Prisma.ProjectCategoryOrderByWithAggregationInput | Prisma.ProjectCategoryOrderByWithAggregationInput[]
  by: Prisma.ProjectCategoryScalarFieldEnum[] | Prisma.ProjectCategoryScalarFieldEnum
  having?: Prisma.ProjectCategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectCategoryCountAggregateInputType | true
  _min?: ProjectCategoryMinAggregateInputType
  _max?: ProjectCategoryMaxAggregateInputType
}

export type ProjectCategoryGroupByOutputType = {
  id: string
  projectId: string
  category: string
  _count: ProjectCategoryCountAggregateOutputType | null
  _min: ProjectCategoryMinAggregateOutputType | null
  _max: ProjectCategoryMaxAggregateOutputType | null
}

export type GetProjectCategoryGroupByPayload<T extends ProjectCategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectCategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectCategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectCategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectCategoryGroupByOutputType[P]>
      }
    >
  >



export type ProjectCategoryWhereInput = {
  AND?: Prisma.ProjectCategoryWhereInput | Prisma.ProjectCategoryWhereInput[]
  OR?: Prisma.ProjectCategoryWhereInput[]
  NOT?: Prisma.ProjectCategoryWhereInput | Prisma.ProjectCategoryWhereInput[]
  id?: Prisma.StringFilter<"ProjectCategory"> | string
  projectId?: Prisma.StringFilter<"ProjectCategory"> | string
  category?: Prisma.StringFilter<"ProjectCategory"> | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type ProjectCategoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type ProjectCategoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  projectId_category?: Prisma.ProjectCategoryProjectIdCategoryCompoundUniqueInput
  AND?: Prisma.ProjectCategoryWhereInput | Prisma.ProjectCategoryWhereInput[]
  OR?: Prisma.ProjectCategoryWhereInput[]
  NOT?: Prisma.ProjectCategoryWhereInput | Prisma.ProjectCategoryWhereInput[]
  projectId?: Prisma.StringFilter<"ProjectCategory"> | string
  category?: Prisma.StringFilter<"ProjectCategory"> | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id" | "projectId_category">

export type ProjectCategoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  _count?: Prisma.ProjectCategoryCountOrderByAggregateInput
  _max?: Prisma.ProjectCategoryMaxOrderByAggregateInput
  _min?: Prisma.ProjectCategoryMinOrderByAggregateInput
}

export type ProjectCategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectCategoryScalarWhereWithAggregatesInput | Prisma.ProjectCategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectCategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectCategoryScalarWhereWithAggregatesInput | Prisma.ProjectCategoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProjectCategory"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"ProjectCategory"> | string
  category?: Prisma.StringWithAggregatesFilter<"ProjectCategory"> | string
}

export type ProjectCategoryCreateInput = {
  id?: string
  category: string
  project: Prisma.ProjectCreateNestedOneWithoutCategoriesInput
}

export type ProjectCategoryUncheckedCreateInput = {
  id?: string
  projectId: string
  category: string
}

export type ProjectCategoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutCategoriesNestedInput
}

export type ProjectCategoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProjectCategoryCreateManyInput = {
  id?: string
  projectId: string
  category: string
}

export type ProjectCategoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProjectCategoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProjectCategoryListRelationFilter = {
  every?: Prisma.ProjectCategoryWhereInput
  some?: Prisma.ProjectCategoryWhereInput
  none?: Prisma.ProjectCategoryWhereInput
}

export type ProjectCategoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjectCategoryProjectIdCategoryCompoundUniqueInput = {
  projectId: string
  category: string
}

export type ProjectCategoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProjectCategoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProjectCategoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProjectCategoryCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectCategoryCreateWithoutProjectInput, Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput> | Prisma.ProjectCategoryCreateWithoutProjectInput[] | Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput | Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectCategoryCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
}

export type ProjectCategoryUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectCategoryCreateWithoutProjectInput, Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput> | Prisma.ProjectCategoryCreateWithoutProjectInput[] | Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput | Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectCategoryCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
}

export type ProjectCategoryUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCategoryCreateWithoutProjectInput, Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput> | Prisma.ProjectCategoryCreateWithoutProjectInput[] | Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput | Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectCategoryUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectCategoryUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectCategoryCreateManyProjectInputEnvelope
  set?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  disconnect?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  delete?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  connect?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  update?: Prisma.ProjectCategoryUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectCategoryUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectCategoryUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectCategoryUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectCategoryScalarWhereInput | Prisma.ProjectCategoryScalarWhereInput[]
}

export type ProjectCategoryUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCategoryCreateWithoutProjectInput, Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput> | Prisma.ProjectCategoryCreateWithoutProjectInput[] | Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput | Prisma.ProjectCategoryCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectCategoryUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectCategoryUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectCategoryCreateManyProjectInputEnvelope
  set?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  disconnect?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  delete?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  connect?: Prisma.ProjectCategoryWhereUniqueInput | Prisma.ProjectCategoryWhereUniqueInput[]
  update?: Prisma.ProjectCategoryUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectCategoryUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectCategoryUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectCategoryUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectCategoryScalarWhereInput | Prisma.ProjectCategoryScalarWhereInput[]
}

export type ProjectCategoryCreateWithoutProjectInput = {
  id?: string
  category: string
}

export type ProjectCategoryUncheckedCreateWithoutProjectInput = {
  id?: string
  category: string
}

export type ProjectCategoryCreateOrConnectWithoutProjectInput = {
  where: Prisma.ProjectCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCategoryCreateWithoutProjectInput, Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput>
}

export type ProjectCategoryCreateManyProjectInputEnvelope = {
  data: Prisma.ProjectCategoryCreateManyProjectInput | Prisma.ProjectCategoryCreateManyProjectInput[]
}

export type ProjectCategoryUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectCategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectCategoryUpdateWithoutProjectInput, Prisma.ProjectCategoryUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ProjectCategoryCreateWithoutProjectInput, Prisma.ProjectCategoryUncheckedCreateWithoutProjectInput>
}

export type ProjectCategoryUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectCategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectCategoryUpdateWithoutProjectInput, Prisma.ProjectCategoryUncheckedUpdateWithoutProjectInput>
}

export type ProjectCategoryUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ProjectCategoryScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectCategoryUpdateManyMutationInput, Prisma.ProjectCategoryUncheckedUpdateManyWithoutProjectInput>
}

export type ProjectCategoryScalarWhereInput = {
  AND?: Prisma.ProjectCategoryScalarWhereInput | Prisma.ProjectCategoryScalarWhereInput[]
  OR?: Prisma.ProjectCategoryScalarWhereInput[]
  NOT?: Prisma.ProjectCategoryScalarWhereInput | Prisma.ProjectCategoryScalarWhereInput[]
  id?: Prisma.StringFilter<"ProjectCategory"> | string
  projectId?: Prisma.StringFilter<"ProjectCategory"> | string
  category?: Prisma.StringFilter<"ProjectCategory"> | string
}

export type ProjectCategoryCreateManyProjectInput = {
  id?: string
  category: string
}

export type ProjectCategoryUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProjectCategoryUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProjectCategoryUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ProjectCategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  category?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectCategory"]>

export type ProjectCategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  category?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectCategory"]>

export type ProjectCategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  category?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectCategory"]>

export type ProjectCategorySelectScalar = {
  id?: boolean
  projectId?: boolean
  category?: boolean
}

export type ProjectCategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "category", ExtArgs["result"]["projectCategory"]>
export type ProjectCategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ProjectCategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ProjectCategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $ProjectCategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProjectCategory"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    category: string
  }, ExtArgs["result"]["projectCategory"]>
  composites: {}
}

export type ProjectCategoryGetPayload<S extends boolean | null | undefined | ProjectCategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload, S>

export type ProjectCategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectCategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectCategoryCountAggregateInputType | true
  }

export interface ProjectCategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProjectCategory'], meta: { name: 'ProjectCategory' } }
  /**
   * Find zero or one ProjectCategory that matches the filter.
   * @param {ProjectCategoryFindUniqueArgs} args - Arguments to find a ProjectCategory
   * @example
   * // Get one ProjectCategory
   * const projectCategory = await prisma.projectCategory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectCategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectCategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProjectCategory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectCategoryFindUniqueOrThrowArgs} args - Arguments to find a ProjectCategory
   * @example
   * // Get one ProjectCategory
   * const projectCategory = await prisma.projectCategory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectCategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectCategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectCategory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCategoryFindFirstArgs} args - Arguments to find a ProjectCategory
   * @example
   * // Get one ProjectCategory
   * const projectCategory = await prisma.projectCategory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectCategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectCategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectCategory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCategoryFindFirstOrThrowArgs} args - Arguments to find a ProjectCategory
   * @example
   * // Get one ProjectCategory
   * const projectCategory = await prisma.projectCategory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectCategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectCategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProjectCategories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProjectCategories
   * const projectCategories = await prisma.projectCategory.findMany()
   * 
   * // Get first 10 ProjectCategories
   * const projectCategories = await prisma.projectCategory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectCategoryWithIdOnly = await prisma.projectCategory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectCategoryFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectCategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProjectCategory.
   * @param {ProjectCategoryCreateArgs} args - Arguments to create a ProjectCategory.
   * @example
   * // Create one ProjectCategory
   * const ProjectCategory = await prisma.projectCategory.create({
   *   data: {
   *     // ... data to create a ProjectCategory
   *   }
   * })
   * 
   */
  create<T extends ProjectCategoryCreateArgs>(args: Prisma.SelectSubset<T, ProjectCategoryCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProjectCategories.
   * @param {ProjectCategoryCreateManyArgs} args - Arguments to create many ProjectCategories.
   * @example
   * // Create many ProjectCategories
   * const projectCategory = await prisma.projectCategory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectCategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectCategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProjectCategories and returns the data saved in the database.
   * @param {ProjectCategoryCreateManyAndReturnArgs} args - Arguments to create many ProjectCategories.
   * @example
   * // Create many ProjectCategories
   * const projectCategory = await prisma.projectCategory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProjectCategories and only return the `id`
   * const projectCategoryWithIdOnly = await prisma.projectCategory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectCategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectCategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProjectCategory.
   * @param {ProjectCategoryDeleteArgs} args - Arguments to delete one ProjectCategory.
   * @example
   * // Delete one ProjectCategory
   * const ProjectCategory = await prisma.projectCategory.delete({
   *   where: {
   *     // ... filter to delete one ProjectCategory
   *   }
   * })
   * 
   */
  delete<T extends ProjectCategoryDeleteArgs>(args: Prisma.SelectSubset<T, ProjectCategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProjectCategory.
   * @param {ProjectCategoryUpdateArgs} args - Arguments to update one ProjectCategory.
   * @example
   * // Update one ProjectCategory
   * const projectCategory = await prisma.projectCategory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectCategoryUpdateArgs>(args: Prisma.SelectSubset<T, ProjectCategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProjectCategories.
   * @param {ProjectCategoryDeleteManyArgs} args - Arguments to filter ProjectCategories to delete.
   * @example
   * // Delete a few ProjectCategories
   * const { count } = await prisma.projectCategory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectCategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectCategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProjectCategories
   * const projectCategory = await prisma.projectCategory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectCategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectCategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectCategories and returns the data updated in the database.
   * @param {ProjectCategoryUpdateManyAndReturnArgs} args - Arguments to update many ProjectCategories.
   * @example
   * // Update many ProjectCategories
   * const projectCategory = await prisma.projectCategory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProjectCategories and only return the `id`
   * const projectCategoryWithIdOnly = await prisma.projectCategory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectCategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectCategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProjectCategory.
   * @param {ProjectCategoryUpsertArgs} args - Arguments to update or create a ProjectCategory.
   * @example
   * // Update or create a ProjectCategory
   * const projectCategory = await prisma.projectCategory.upsert({
   *   create: {
   *     // ... data to create a ProjectCategory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProjectCategory we want to update
   *   }
   * })
   */
  upsert<T extends ProjectCategoryUpsertArgs>(args: Prisma.SelectSubset<T, ProjectCategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectCategoryClient<runtime.Types.Result.GetResult<Prisma.$ProjectCategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProjectCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCategoryCountArgs} args - Arguments to filter ProjectCategories to count.
   * @example
   * // Count the number of ProjectCategories
   * const count = await prisma.projectCategory.count({
   *   where: {
   *     // ... the filter for the ProjectCategories we want to count
   *   }
   * })
  **/
  count<T extends ProjectCategoryCountArgs>(
    args?: Prisma.Subset<T, ProjectCategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectCategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProjectCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectCategoryAggregateArgs>(args: Prisma.Subset<T, ProjectCategoryAggregateArgs>): Prisma.PrismaPromise<GetProjectCategoryAggregateType<T>>

  /**
   * Group by ProjectCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectCategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectCategoryGroupByArgs['orderBy'] }
      : { orderBy?: ProjectCategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectCategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProjectCategory model
 */
readonly fields: ProjectCategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProjectCategory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectCategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProjectCategory model
 */
export interface ProjectCategoryFieldRefs {
  readonly id: Prisma.FieldRef<"ProjectCategory", 'String'>
  readonly projectId: Prisma.FieldRef<"ProjectCategory", 'String'>
  readonly category: Prisma.FieldRef<"ProjectCategory", 'String'>
}
    

// Custom InputTypes
/**
 * ProjectCategory findUnique
 */
export type ProjectCategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProjectCategory to fetch.
   */
  where: Prisma.ProjectCategoryWhereUniqueInput
}

/**
 * ProjectCategory findUniqueOrThrow
 */
export type ProjectCategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProjectCategory to fetch.
   */
  where: Prisma.ProjectCategoryWhereUniqueInput
}

/**
 * ProjectCategory findFirst
 */
export type ProjectCategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProjectCategory to fetch.
   */
  where?: Prisma.ProjectCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectCategories to fetch.
   */
  orderBy?: Prisma.ProjectCategoryOrderByWithRelationInput | Prisma.ProjectCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectCategories.
   */
  cursor?: Prisma.ProjectCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectCategories.
   */
  distinct?: Prisma.ProjectCategoryScalarFieldEnum | Prisma.ProjectCategoryScalarFieldEnum[]
}

/**
 * ProjectCategory findFirstOrThrow
 */
export type ProjectCategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProjectCategory to fetch.
   */
  where?: Prisma.ProjectCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectCategories to fetch.
   */
  orderBy?: Prisma.ProjectCategoryOrderByWithRelationInput | Prisma.ProjectCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectCategories.
   */
  cursor?: Prisma.ProjectCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectCategories.
   */
  distinct?: Prisma.ProjectCategoryScalarFieldEnum | Prisma.ProjectCategoryScalarFieldEnum[]
}

/**
 * ProjectCategory findMany
 */
export type ProjectCategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ProjectCategories to fetch.
   */
  where?: Prisma.ProjectCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectCategories to fetch.
   */
  orderBy?: Prisma.ProjectCategoryOrderByWithRelationInput | Prisma.ProjectCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProjectCategories.
   */
  cursor?: Prisma.ProjectCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectCategories.
   */
  distinct?: Prisma.ProjectCategoryScalarFieldEnum | Prisma.ProjectCategoryScalarFieldEnum[]
}

/**
 * ProjectCategory create
 */
export type ProjectCategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a ProjectCategory.
   */
  data: Prisma.XOR<Prisma.ProjectCategoryCreateInput, Prisma.ProjectCategoryUncheckedCreateInput>
}

/**
 * ProjectCategory createMany
 */
export type ProjectCategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProjectCategories.
   */
  data: Prisma.ProjectCategoryCreateManyInput | Prisma.ProjectCategoryCreateManyInput[]
}

/**
 * ProjectCategory createManyAndReturn
 */
export type ProjectCategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * The data used to create many ProjectCategories.
   */
  data: Prisma.ProjectCategoryCreateManyInput | Prisma.ProjectCategoryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectCategory update
 */
export type ProjectCategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a ProjectCategory.
   */
  data: Prisma.XOR<Prisma.ProjectCategoryUpdateInput, Prisma.ProjectCategoryUncheckedUpdateInput>
  /**
   * Choose, which ProjectCategory to update.
   */
  where: Prisma.ProjectCategoryWhereUniqueInput
}

/**
 * ProjectCategory updateMany
 */
export type ProjectCategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProjectCategories.
   */
  data: Prisma.XOR<Prisma.ProjectCategoryUpdateManyMutationInput, Prisma.ProjectCategoryUncheckedUpdateManyInput>
  /**
   * Filter which ProjectCategories to update
   */
  where?: Prisma.ProjectCategoryWhereInput
  /**
   * Limit how many ProjectCategories to update.
   */
  limit?: number
}

/**
 * ProjectCategory updateManyAndReturn
 */
export type ProjectCategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * The data used to update ProjectCategories.
   */
  data: Prisma.XOR<Prisma.ProjectCategoryUpdateManyMutationInput, Prisma.ProjectCategoryUncheckedUpdateManyInput>
  /**
   * Filter which ProjectCategories to update
   */
  where?: Prisma.ProjectCategoryWhereInput
  /**
   * Limit how many ProjectCategories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectCategory upsert
 */
export type ProjectCategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the ProjectCategory to update in case it exists.
   */
  where: Prisma.ProjectCategoryWhereUniqueInput
  /**
   * In case the ProjectCategory found by the `where` argument doesn't exist, create a new ProjectCategory with this data.
   */
  create: Prisma.XOR<Prisma.ProjectCategoryCreateInput, Prisma.ProjectCategoryUncheckedCreateInput>
  /**
   * In case the ProjectCategory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectCategoryUpdateInput, Prisma.ProjectCategoryUncheckedUpdateInput>
}

/**
 * ProjectCategory delete
 */
export type ProjectCategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
  /**
   * Filter which ProjectCategory to delete.
   */
  where: Prisma.ProjectCategoryWhereUniqueInput
}

/**
 * ProjectCategory deleteMany
 */
export type ProjectCategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectCategories to delete
   */
  where?: Prisma.ProjectCategoryWhereInput
  /**
   * Limit how many ProjectCategories to delete.
   */
  limit?: number
}

/**
 * ProjectCategory without action
 */
export type ProjectCategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCategory
   */
  select?: Prisma.ProjectCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectCategory
   */
  omit?: Prisma.ProjectCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectCategoryInclude<ExtArgs> | null
}
