
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProjectTechStack` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProjectTechStack
 * 
 */
export type ProjectTechStackModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectTechStackPayload>

export type AggregateProjectTechStack = {
  _count: ProjectTechStackCountAggregateOutputType | null
  _min: ProjectTechStackMinAggregateOutputType | null
  _max: ProjectTechStackMaxAggregateOutputType | null
}

export type ProjectTechStackMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  techName: string | null
  category: $Enums.TechCategory | null
}

export type ProjectTechStackMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  techName: string | null
  category: $Enums.TechCategory | null
}

export type ProjectTechStackCountAggregateOutputType = {
  id: number
  projectId: number
  techName: number
  category: number
  _all: number
}


export type ProjectTechStackMinAggregateInputType = {
  id?: true
  projectId?: true
  techName?: true
  category?: true
}

export type ProjectTechStackMaxAggregateInputType = {
  id?: true
  projectId?: true
  techName?: true
  category?: true
}

export type ProjectTechStackCountAggregateInputType = {
  id?: true
  projectId?: true
  techName?: true
  category?: true
  _all?: true
}

export type ProjectTechStackAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectTechStack to aggregate.
   */
  where?: Prisma.ProjectTechStackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTechStacks to fetch.
   */
  orderBy?: Prisma.ProjectTechStackOrderByWithRelationInput | Prisma.ProjectTechStackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectTechStackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTechStacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTechStacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProjectTechStacks
  **/
  _count?: true | ProjectTechStackCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectTechStackMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectTechStackMaxAggregateInputType
}

export type GetProjectTechStackAggregateType<T extends ProjectTechStackAggregateArgs> = {
      [P in keyof T & keyof AggregateProjectTechStack]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProjectTechStack[P]>
    : Prisma.GetScalarType<T[P], AggregateProjectTechStack[P]>
}




export type ProjectTechStackGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectTechStackWhereInput
  orderBy?: Prisma.ProjectTechStackOrderByWithAggregationInput | Prisma.ProjectTechStackOrderByWithAggregationInput[]
  by: Prisma.ProjectTechStackScalarFieldEnum[] | Prisma.ProjectTechStackScalarFieldEnum
  having?: Prisma.ProjectTechStackScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectTechStackCountAggregateInputType | true
  _min?: ProjectTechStackMinAggregateInputType
  _max?: ProjectTechStackMaxAggregateInputType
}

export type ProjectTechStackGroupByOutputType = {
  id: string
  projectId: string
  techName: string
  category: $Enums.TechCategory
  _count: ProjectTechStackCountAggregateOutputType | null
  _min: ProjectTechStackMinAggregateOutputType | null
  _max: ProjectTechStackMaxAggregateOutputType | null
}

export type GetProjectTechStackGroupByPayload<T extends ProjectTechStackGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectTechStackGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectTechStackGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectTechStackGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectTechStackGroupByOutputType[P]>
      }
    >
  >



export type ProjectTechStackWhereInput = {
  AND?: Prisma.ProjectTechStackWhereInput | Prisma.ProjectTechStackWhereInput[]
  OR?: Prisma.ProjectTechStackWhereInput[]
  NOT?: Prisma.ProjectTechStackWhereInput | Prisma.ProjectTechStackWhereInput[]
  id?: Prisma.StringFilter<"ProjectTechStack"> | string
  projectId?: Prisma.StringFilter<"ProjectTechStack"> | string
  techName?: Prisma.StringFilter<"ProjectTechStack"> | string
  category?: Prisma.EnumTechCategoryFilter<"ProjectTechStack"> | $Enums.TechCategory
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type ProjectTechStackOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  techName?: Prisma.SortOrder
  category?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type ProjectTechStackWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  projectId_techName?: Prisma.ProjectTechStackProjectIdTechNameCompoundUniqueInput
  AND?: Prisma.ProjectTechStackWhereInput | Prisma.ProjectTechStackWhereInput[]
  OR?: Prisma.ProjectTechStackWhereInput[]
  NOT?: Prisma.ProjectTechStackWhereInput | Prisma.ProjectTechStackWhereInput[]
  projectId?: Prisma.StringFilter<"ProjectTechStack"> | string
  techName?: Prisma.StringFilter<"ProjectTechStack"> | string
  category?: Prisma.EnumTechCategoryFilter<"ProjectTechStack"> | $Enums.TechCategory
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id" | "projectId_techName">

export type ProjectTechStackOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  techName?: Prisma.SortOrder
  category?: Prisma.SortOrder
  _count?: Prisma.ProjectTechStackCountOrderByAggregateInput
  _max?: Prisma.ProjectTechStackMaxOrderByAggregateInput
  _min?: Prisma.ProjectTechStackMinOrderByAggregateInput
}

export type ProjectTechStackScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectTechStackScalarWhereWithAggregatesInput | Prisma.ProjectTechStackScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectTechStackScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectTechStackScalarWhereWithAggregatesInput | Prisma.ProjectTechStackScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProjectTechStack"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"ProjectTechStack"> | string
  techName?: Prisma.StringWithAggregatesFilter<"ProjectTechStack"> | string
  category?: Prisma.EnumTechCategoryWithAggregatesFilter<"ProjectTechStack"> | $Enums.TechCategory
}

export type ProjectTechStackCreateInput = {
  id?: string
  techName: string
  category?: $Enums.TechCategory
  project: Prisma.ProjectCreateNestedOneWithoutTechStackInput
}

export type ProjectTechStackUncheckedCreateInput = {
  id?: string
  projectId: string
  techName: string
  category?: $Enums.TechCategory
}

export type ProjectTechStackUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  techName?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumTechCategoryFieldUpdateOperationsInput | $Enums.TechCategory
  project?: Prisma.ProjectUpdateOneRequiredWithoutTechStackNestedInput
}

export type ProjectTechStackUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  techName?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumTechCategoryFieldUpdateOperationsInput | $Enums.TechCategory
}

export type ProjectTechStackCreateManyInput = {
  id?: string
  projectId: string
  techName: string
  category?: $Enums.TechCategory
}

export type ProjectTechStackUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  techName?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumTechCategoryFieldUpdateOperationsInput | $Enums.TechCategory
}

export type ProjectTechStackUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  techName?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumTechCategoryFieldUpdateOperationsInput | $Enums.TechCategory
}

export type ProjectTechStackListRelationFilter = {
  every?: Prisma.ProjectTechStackWhereInput
  some?: Prisma.ProjectTechStackWhereInput
  none?: Prisma.ProjectTechStackWhereInput
}

export type ProjectTechStackOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjectTechStackProjectIdTechNameCompoundUniqueInput = {
  projectId: string
  techName: string
}

export type ProjectTechStackCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  techName?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProjectTechStackMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  techName?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProjectTechStackMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  techName?: Prisma.SortOrder
  category?: Prisma.SortOrder
}

export type ProjectTechStackCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectTechStackCreateWithoutProjectInput, Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput> | Prisma.ProjectTechStackCreateWithoutProjectInput[] | Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput | Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectTechStackCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
}

export type ProjectTechStackUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectTechStackCreateWithoutProjectInput, Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput> | Prisma.ProjectTechStackCreateWithoutProjectInput[] | Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput | Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectTechStackCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
}

export type ProjectTechStackUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectTechStackCreateWithoutProjectInput, Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput> | Prisma.ProjectTechStackCreateWithoutProjectInput[] | Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput | Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectTechStackUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectTechStackUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectTechStackCreateManyProjectInputEnvelope
  set?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  disconnect?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  delete?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  connect?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  update?: Prisma.ProjectTechStackUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectTechStackUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectTechStackUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectTechStackUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectTechStackScalarWhereInput | Prisma.ProjectTechStackScalarWhereInput[]
}

export type ProjectTechStackUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectTechStackCreateWithoutProjectInput, Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput> | Prisma.ProjectTechStackCreateWithoutProjectInput[] | Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput | Prisma.ProjectTechStackCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectTechStackUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectTechStackUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectTechStackCreateManyProjectInputEnvelope
  set?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  disconnect?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  delete?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  connect?: Prisma.ProjectTechStackWhereUniqueInput | Prisma.ProjectTechStackWhereUniqueInput[]
  update?: Prisma.ProjectTechStackUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectTechStackUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectTechStackUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectTechStackUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectTechStackScalarWhereInput | Prisma.ProjectTechStackScalarWhereInput[]
}

export type EnumTechCategoryFieldUpdateOperationsInput = {
  set?: $Enums.TechCategory
}

export type ProjectTechStackCreateWithoutProjectInput = {
  id?: string
  techName: string
  category?: $Enums.TechCategory
}

export type ProjectTechStackUncheckedCreateWithoutProjectInput = {
  id?: string
  techName: string
  category?: $Enums.TechCategory
}

export type ProjectTechStackCreateOrConnectWithoutProjectInput = {
  where: Prisma.ProjectTechStackWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectTechStackCreateWithoutProjectInput, Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput>
}

export type ProjectTechStackCreateManyProjectInputEnvelope = {
  data: Prisma.ProjectTechStackCreateManyProjectInput | Prisma.ProjectTechStackCreateManyProjectInput[]
}

export type ProjectTechStackUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectTechStackWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectTechStackUpdateWithoutProjectInput, Prisma.ProjectTechStackUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ProjectTechStackCreateWithoutProjectInput, Prisma.ProjectTechStackUncheckedCreateWithoutProjectInput>
}

export type ProjectTechStackUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectTechStackWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectTechStackUpdateWithoutProjectInput, Prisma.ProjectTechStackUncheckedUpdateWithoutProjectInput>
}

export type ProjectTechStackUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ProjectTechStackScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectTechStackUpdateManyMutationInput, Prisma.ProjectTechStackUncheckedUpdateManyWithoutProjectInput>
}

export type ProjectTechStackScalarWhereInput = {
  AND?: Prisma.ProjectTechStackScalarWhereInput | Prisma.ProjectTechStackScalarWhereInput[]
  OR?: Prisma.ProjectTechStackScalarWhereInput[]
  NOT?: Prisma.ProjectTechStackScalarWhereInput | Prisma.ProjectTechStackScalarWhereInput[]
  id?: Prisma.StringFilter<"ProjectTechStack"> | string
  projectId?: Prisma.StringFilter<"ProjectTechStack"> | string
  techName?: Prisma.StringFilter<"ProjectTechStack"> | string
  category?: Prisma.EnumTechCategoryFilter<"ProjectTechStack"> | $Enums.TechCategory
}

export type ProjectTechStackCreateManyProjectInput = {
  id?: string
  techName: string
  category?: $Enums.TechCategory
}

export type ProjectTechStackUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  techName?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumTechCategoryFieldUpdateOperationsInput | $Enums.TechCategory
}

export type ProjectTechStackUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  techName?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumTechCategoryFieldUpdateOperationsInput | $Enums.TechCategory
}

export type ProjectTechStackUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  techName?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumTechCategoryFieldUpdateOperationsInput | $Enums.TechCategory
}



export type ProjectTechStackSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  techName?: boolean
  category?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectTechStack"]>

export type ProjectTechStackSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  techName?: boolean
  category?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectTechStack"]>

export type ProjectTechStackSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  techName?: boolean
  category?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectTechStack"]>

export type ProjectTechStackSelectScalar = {
  id?: boolean
  projectId?: boolean
  techName?: boolean
  category?: boolean
}

export type ProjectTechStackOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "techName" | "category", ExtArgs["result"]["projectTechStack"]>
export type ProjectTechStackInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ProjectTechStackIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ProjectTechStackIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $ProjectTechStackPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProjectTechStack"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    techName: string
    category: $Enums.TechCategory
  }, ExtArgs["result"]["projectTechStack"]>
  composites: {}
}

export type ProjectTechStackGetPayload<S extends boolean | null | undefined | ProjectTechStackDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload, S>

export type ProjectTechStackCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectTechStackFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectTechStackCountAggregateInputType | true
  }

export interface ProjectTechStackDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProjectTechStack'], meta: { name: 'ProjectTechStack' } }
  /**
   * Find zero or one ProjectTechStack that matches the filter.
   * @param {ProjectTechStackFindUniqueArgs} args - Arguments to find a ProjectTechStack
   * @example
   * // Get one ProjectTechStack
   * const projectTechStack = await prisma.projectTechStack.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectTechStackFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectTechStackFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProjectTechStack that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectTechStackFindUniqueOrThrowArgs} args - Arguments to find a ProjectTechStack
   * @example
   * // Get one ProjectTechStack
   * const projectTechStack = await prisma.projectTechStack.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectTechStackFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectTechStackFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectTechStack that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTechStackFindFirstArgs} args - Arguments to find a ProjectTechStack
   * @example
   * // Get one ProjectTechStack
   * const projectTechStack = await prisma.projectTechStack.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectTechStackFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectTechStackFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectTechStack that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTechStackFindFirstOrThrowArgs} args - Arguments to find a ProjectTechStack
   * @example
   * // Get one ProjectTechStack
   * const projectTechStack = await prisma.projectTechStack.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectTechStackFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectTechStackFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProjectTechStacks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTechStackFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProjectTechStacks
   * const projectTechStacks = await prisma.projectTechStack.findMany()
   * 
   * // Get first 10 ProjectTechStacks
   * const projectTechStacks = await prisma.projectTechStack.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectTechStackWithIdOnly = await prisma.projectTechStack.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectTechStackFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectTechStackFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProjectTechStack.
   * @param {ProjectTechStackCreateArgs} args - Arguments to create a ProjectTechStack.
   * @example
   * // Create one ProjectTechStack
   * const ProjectTechStack = await prisma.projectTechStack.create({
   *   data: {
   *     // ... data to create a ProjectTechStack
   *   }
   * })
   * 
   */
  create<T extends ProjectTechStackCreateArgs>(args: Prisma.SelectSubset<T, ProjectTechStackCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProjectTechStacks.
   * @param {ProjectTechStackCreateManyArgs} args - Arguments to create many ProjectTechStacks.
   * @example
   * // Create many ProjectTechStacks
   * const projectTechStack = await prisma.projectTechStack.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectTechStackCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectTechStackCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProjectTechStacks and returns the data saved in the database.
   * @param {ProjectTechStackCreateManyAndReturnArgs} args - Arguments to create many ProjectTechStacks.
   * @example
   * // Create many ProjectTechStacks
   * const projectTechStack = await prisma.projectTechStack.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProjectTechStacks and only return the `id`
   * const projectTechStackWithIdOnly = await prisma.projectTechStack.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectTechStackCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectTechStackCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProjectTechStack.
   * @param {ProjectTechStackDeleteArgs} args - Arguments to delete one ProjectTechStack.
   * @example
   * // Delete one ProjectTechStack
   * const ProjectTechStack = await prisma.projectTechStack.delete({
   *   where: {
   *     // ... filter to delete one ProjectTechStack
   *   }
   * })
   * 
   */
  delete<T extends ProjectTechStackDeleteArgs>(args: Prisma.SelectSubset<T, ProjectTechStackDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProjectTechStack.
   * @param {ProjectTechStackUpdateArgs} args - Arguments to update one ProjectTechStack.
   * @example
   * // Update one ProjectTechStack
   * const projectTechStack = await prisma.projectTechStack.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectTechStackUpdateArgs>(args: Prisma.SelectSubset<T, ProjectTechStackUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProjectTechStacks.
   * @param {ProjectTechStackDeleteManyArgs} args - Arguments to filter ProjectTechStacks to delete.
   * @example
   * // Delete a few ProjectTechStacks
   * const { count } = await prisma.projectTechStack.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectTechStackDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectTechStackDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectTechStacks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTechStackUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProjectTechStacks
   * const projectTechStack = await prisma.projectTechStack.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectTechStackUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectTechStackUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectTechStacks and returns the data updated in the database.
   * @param {ProjectTechStackUpdateManyAndReturnArgs} args - Arguments to update many ProjectTechStacks.
   * @example
   * // Update many ProjectTechStacks
   * const projectTechStack = await prisma.projectTechStack.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProjectTechStacks and only return the `id`
   * const projectTechStackWithIdOnly = await prisma.projectTechStack.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectTechStackUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectTechStackUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProjectTechStack.
   * @param {ProjectTechStackUpsertArgs} args - Arguments to update or create a ProjectTechStack.
   * @example
   * // Update or create a ProjectTechStack
   * const projectTechStack = await prisma.projectTechStack.upsert({
   *   create: {
   *     // ... data to create a ProjectTechStack
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProjectTechStack we want to update
   *   }
   * })
   */
  upsert<T extends ProjectTechStackUpsertArgs>(args: Prisma.SelectSubset<T, ProjectTechStackUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectTechStackClient<runtime.Types.Result.GetResult<Prisma.$ProjectTechStackPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProjectTechStacks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTechStackCountArgs} args - Arguments to filter ProjectTechStacks to count.
   * @example
   * // Count the number of ProjectTechStacks
   * const count = await prisma.projectTechStack.count({
   *   where: {
   *     // ... the filter for the ProjectTechStacks we want to count
   *   }
   * })
  **/
  count<T extends ProjectTechStackCountArgs>(
    args?: Prisma.Subset<T, ProjectTechStackCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectTechStackCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProjectTechStack.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTechStackAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectTechStackAggregateArgs>(args: Prisma.Subset<T, ProjectTechStackAggregateArgs>): Prisma.PrismaPromise<GetProjectTechStackAggregateType<T>>

  /**
   * Group by ProjectTechStack.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTechStackGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectTechStackGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectTechStackGroupByArgs['orderBy'] }
      : { orderBy?: ProjectTechStackGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectTechStackGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectTechStackGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProjectTechStack model
 */
readonly fields: ProjectTechStackFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProjectTechStack.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectTechStackClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProjectTechStack model
 */
export interface ProjectTechStackFieldRefs {
  readonly id: Prisma.FieldRef<"ProjectTechStack", 'String'>
  readonly projectId: Prisma.FieldRef<"ProjectTechStack", 'String'>
  readonly techName: Prisma.FieldRef<"ProjectTechStack", 'String'>
  readonly category: Prisma.FieldRef<"ProjectTechStack", 'TechCategory'>
}
    

// Custom InputTypes
/**
 * ProjectTechStack findUnique
 */
export type ProjectTechStackFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTechStack to fetch.
   */
  where: Prisma.ProjectTechStackWhereUniqueInput
}

/**
 * ProjectTechStack findUniqueOrThrow
 */
export type ProjectTechStackFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTechStack to fetch.
   */
  where: Prisma.ProjectTechStackWhereUniqueInput
}

/**
 * ProjectTechStack findFirst
 */
export type ProjectTechStackFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTechStack to fetch.
   */
  where?: Prisma.ProjectTechStackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTechStacks to fetch.
   */
  orderBy?: Prisma.ProjectTechStackOrderByWithRelationInput | Prisma.ProjectTechStackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectTechStacks.
   */
  cursor?: Prisma.ProjectTechStackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTechStacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTechStacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectTechStacks.
   */
  distinct?: Prisma.ProjectTechStackScalarFieldEnum | Prisma.ProjectTechStackScalarFieldEnum[]
}

/**
 * ProjectTechStack findFirstOrThrow
 */
export type ProjectTechStackFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTechStack to fetch.
   */
  where?: Prisma.ProjectTechStackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTechStacks to fetch.
   */
  orderBy?: Prisma.ProjectTechStackOrderByWithRelationInput | Prisma.ProjectTechStackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectTechStacks.
   */
  cursor?: Prisma.ProjectTechStackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTechStacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTechStacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectTechStacks.
   */
  distinct?: Prisma.ProjectTechStackScalarFieldEnum | Prisma.ProjectTechStackScalarFieldEnum[]
}

/**
 * ProjectTechStack findMany
 */
export type ProjectTechStackFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTechStacks to fetch.
   */
  where?: Prisma.ProjectTechStackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTechStacks to fetch.
   */
  orderBy?: Prisma.ProjectTechStackOrderByWithRelationInput | Prisma.ProjectTechStackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProjectTechStacks.
   */
  cursor?: Prisma.ProjectTechStackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTechStacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTechStacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectTechStacks.
   */
  distinct?: Prisma.ProjectTechStackScalarFieldEnum | Prisma.ProjectTechStackScalarFieldEnum[]
}

/**
 * ProjectTechStack create
 */
export type ProjectTechStackCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * The data needed to create a ProjectTechStack.
   */
  data: Prisma.XOR<Prisma.ProjectTechStackCreateInput, Prisma.ProjectTechStackUncheckedCreateInput>
}

/**
 * ProjectTechStack createMany
 */
export type ProjectTechStackCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProjectTechStacks.
   */
  data: Prisma.ProjectTechStackCreateManyInput | Prisma.ProjectTechStackCreateManyInput[]
}

/**
 * ProjectTechStack createManyAndReturn
 */
export type ProjectTechStackCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * The data used to create many ProjectTechStacks.
   */
  data: Prisma.ProjectTechStackCreateManyInput | Prisma.ProjectTechStackCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectTechStack update
 */
export type ProjectTechStackUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * The data needed to update a ProjectTechStack.
   */
  data: Prisma.XOR<Prisma.ProjectTechStackUpdateInput, Prisma.ProjectTechStackUncheckedUpdateInput>
  /**
   * Choose, which ProjectTechStack to update.
   */
  where: Prisma.ProjectTechStackWhereUniqueInput
}

/**
 * ProjectTechStack updateMany
 */
export type ProjectTechStackUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProjectTechStacks.
   */
  data: Prisma.XOR<Prisma.ProjectTechStackUpdateManyMutationInput, Prisma.ProjectTechStackUncheckedUpdateManyInput>
  /**
   * Filter which ProjectTechStacks to update
   */
  where?: Prisma.ProjectTechStackWhereInput
  /**
   * Limit how many ProjectTechStacks to update.
   */
  limit?: number
}

/**
 * ProjectTechStack updateManyAndReturn
 */
export type ProjectTechStackUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * The data used to update ProjectTechStacks.
   */
  data: Prisma.XOR<Prisma.ProjectTechStackUpdateManyMutationInput, Prisma.ProjectTechStackUncheckedUpdateManyInput>
  /**
   * Filter which ProjectTechStacks to update
   */
  where?: Prisma.ProjectTechStackWhereInput
  /**
   * Limit how many ProjectTechStacks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectTechStack upsert
 */
export type ProjectTechStackUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * The filter to search for the ProjectTechStack to update in case it exists.
   */
  where: Prisma.ProjectTechStackWhereUniqueInput
  /**
   * In case the ProjectTechStack found by the `where` argument doesn't exist, create a new ProjectTechStack with this data.
   */
  create: Prisma.XOR<Prisma.ProjectTechStackCreateInput, Prisma.ProjectTechStackUncheckedCreateInput>
  /**
   * In case the ProjectTechStack was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectTechStackUpdateInput, Prisma.ProjectTechStackUncheckedUpdateInput>
}

/**
 * ProjectTechStack delete
 */
export type ProjectTechStackDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
  /**
   * Filter which ProjectTechStack to delete.
   */
  where: Prisma.ProjectTechStackWhereUniqueInput
}

/**
 * ProjectTechStack deleteMany
 */
export type ProjectTechStackDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectTechStacks to delete
   */
  where?: Prisma.ProjectTechStackWhereInput
  /**
   * Limit how many ProjectTechStacks to delete.
   */
  limit?: number
}

/**
 * ProjectTechStack without action
 */
export type ProjectTechStackDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTechStack
   */
  select?: Prisma.ProjectTechStackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTechStack
   */
  omit?: Prisma.ProjectTechStackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTechStackInclude<ExtArgs> | null
}
